# -*- coding: utf-8 -*-
"""Currentcalibaration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IH2dWRLEd4SwOMUGVGX-JfxhAJvjo76W
"""

import numpy as np
import matplotlib.pyplot as plt

def calibrate_range(name, raw_data, actual_data, degree=1):
    """
    Performs polynomial regression and prints C-style coefficients.
    """
    coeffs = np.polyfit(raw_data, actual_data, degree)
    p = np.poly1d(coeffs)

    print(f"\n--- {name} Calibration ---")
    print(f"Polynomial Degree: {degree}")
    for i, c in enumerate(coeffs):
        power = degree - i
        print(f"coeff_x{power} = {c:.12e}f;")

    # Plotting
    plt.scatter(raw_data, actual_data, label=f'{name} Data')
    plt.plot(raw_data, p(raw_data), label=f'{name} Fit')
    return coeffs

# --- DATASET 1: Milli-Amps (33 Ohm Resistor) ---
# Format: [Raw ADC Values], [Actual mA Values]
raw_ma = np.array([979.0773, 1352.591, 1927.132, 2124.436, 2409.845, 2676.641, 3097.309])
actual_ma = np.array([35, 46, 67, 71, 82, 91, 104])

# --- DATASET 2: Micro-Amps (0.25 Ohm + Op-Amp) ---
# Format: [Raw ADC Values], [Actual uA Values]
raw_ua = np.array([0.04095, 2.0475, 4.095, 6.1425, 8.19, 10.2375, 12.285, 14.3325, 16.38, 18.4275, 20.475, 22.5225, 24.57, 26.6175, 28.665, 30.7125, 32.76, 34.8075, 36.855])
actual_ua = np.array([1, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900 ])

# Run Calibration
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
ma_coeffs = calibrate_range("Milli-Amp Range", raw_ma, actual_ma, degree=1) # Linear usually best for high range
plt.ylabel("Actual Current (mA)")
plt.xlabel("Raw ADC Value")
plt.legend()

plt.subplot(1, 2, 2)
ua_coeffs = calibrate_range("Micro-Amp Range", raw_ua, actual_ua, degree=2) # 2nd degree helps with Op-Amp offset
plt.ylabel("Actual Current (uA)")
plt.xlabel("Raw ADC Value")
plt.legend()

plt.tight_layout()
plt.show()