# -*- coding: utf-8 -*-
"""VoltageCalibaration

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11jH8UiIf9ixfnoVtuCETILBlND33JZtA
"""

import numpy as np
import matplotlib.pyplot as plt

# 1. Your Data Collections
# Replace these with your actual measured values
raw_adc = np.array([11.168,203.5091,290.3727,384.6818,488.9182,585.7091,686.2227,787.9773,876.0818,966.6682,1068.423,1163.973,1270.691,1374.927,1463.032,1553.618,1659.095,1763.332,1857.641,1956.914,2052.464,2154.218,2244.805,2340.355])
actual_voltage = np.array([0,1.0,1.5,2.0,2.5,3.0,3.5,4.0,4.5,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0])

# 2. Fit the Polynomial (Degree 2 is usually plenty for ADC calibration)
# Use degree=1 for a straight line (linear)
degree = 2
coefficients = np.polyfit(raw_adc, actual_voltage, degree)

# 3. Create a function from those coefficients
poly_func = np.poly1d(coefficients)

print(f"Polynomial Coefficients: {coefficients}")
print("-" * 30)
print(f"Equation: \n{poly_func}")

# 4. Predict a value
sample_adc = 550
predicted_v = poly_func(sample_adc)
print(f"\nPredicted voltage for ADC {sample_adc}: {predicted_v:.4f}V")

# 5. Visualization (Optional)
plt.scatter(raw_adc, actual_voltage, color='red', label='Actual Data')
plt.plot(raw_adc, poly_func(raw_adc), label=f'Polynomial (Degree {degree})')
plt.xlabel('Raw ADC Value')
plt.ylabel('Voltage (V)')
plt.legend()
plt.show()